name: gonuxt-starter

services:
  api:
    
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://root:gonuxtsecret@postgres:5432/gonuxt

  postgres:
    image: postgres:latest
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=gonuxtsecret
      - POSTGRES_DB=gonuxt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d gonuxt"]
      interval: 5s
      retries: 5
      timeout: 3s
  
