// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: service_gonuxt_auth.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_service_gonuxt_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gonuxt_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_service_gonuxt_auth_proto_rawDescGZIP(), []int{0}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_service_gonuxt_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gonuxt_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_service_gonuxt_auth_proto_rawDescGZIP(), []int{1}
}

type GoogleLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginRequest) Reset() {
	*x = GoogleLoginRequest{}
	mi := &file_service_gonuxt_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginRequest) ProtoMessage() {}

func (x *GoogleLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gonuxt_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginRequest.ProtoReflect.Descriptor instead.
func (*GoogleLoginRequest) Descriptor() ([]byte, []int) {
	return file_service_gonuxt_auth_proto_rawDescGZIP(), []int{2}
}

type GoogleLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedirectUrl   string                 `protobuf:"bytes,1,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleLoginResponse) Reset() {
	*x = GoogleLoginResponse{}
	mi := &file_service_gonuxt_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleLoginResponse) ProtoMessage() {}

func (x *GoogleLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gonuxt_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleLoginResponse.ProtoReflect.Descriptor instead.
func (*GoogleLoginResponse) Descriptor() ([]byte, []int) {
	return file_service_gonuxt_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GoogleLoginResponse) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

type GoogleCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCallbackRequest) Reset() {
	*x = GoogleCallbackRequest{}
	mi := &file_service_gonuxt_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCallbackRequest) ProtoMessage() {}

func (x *GoogleCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gonuxt_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCallbackRequest.ProtoReflect.Descriptor instead.
func (*GoogleCallbackRequest) Descriptor() ([]byte, []int) {
	return file_service_gonuxt_auth_proto_rawDescGZIP(), []int{4}
}

func (x *GoogleCallbackRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GoogleCallbackRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type GoogleCallbackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoogleCallbackResponse) Reset() {
	*x = GoogleCallbackResponse{}
	mi := &file_service_gonuxt_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoogleCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoogleCallbackResponse) ProtoMessage() {}

func (x *GoogleCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gonuxt_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoogleCallbackResponse.ProtoReflect.Descriptor instead.
func (*GoogleCallbackResponse) Descriptor() ([]byte, []int) {
	return file_service_gonuxt_auth_proto_rawDescGZIP(), []int{5}
}

func (x *GoogleCallbackResponse) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

var File_service_gonuxt_auth_proto protoreflect.FileDescriptor

const file_service_gonuxt_auth_proto_rawDesc = "" +
	"\n" +
	"\x19service_gonuxt_auth.proto\x12\x02pb\x1a\x15rpc_create_user.proto\x1a\x14rpc_login_user.proto\x1a\x1cgoogle/api/annotations.proto\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"\x14\n" +
	"\x12GoogleLoginRequest\"8\n" +
	"\x13GoogleLoginResponse\x12!\n" +
	"\fredirect_url\x18\x01 \x01(\tR\vredirectUrl\"A\n" +
	"\x15GoogleCallbackRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"5\n" +
	"\x16GoogleCallbackResponse\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken2\xce\x03\n" +
	"\x04Auth\x12]\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/auth/email/create\x12Y\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/auth/email/login\x12W\n" +
	"\vGoogleLogin\x12\x16.pb.GoogleLoginRequest\x1a\x17.pb.GoogleLoginResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/auth/google\x12i\n" +
	"\x0eGoogleCallback\x12\x19.pb.GoogleCallbackRequest\x1a\x1a.pb.GoogleCallbackResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/v1/auth/google/callback\x12H\n" +
	"\x06Logout\x12\x11.pb.LogoutRequest\x1a\x12.pb.LogoutResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/auth/logoutB.Z,github.com/noueii/gonuxt-starter/internal/pbb\x06proto3"

var (
	file_service_gonuxt_auth_proto_rawDescOnce sync.Once
	file_service_gonuxt_auth_proto_rawDescData []byte
)

func file_service_gonuxt_auth_proto_rawDescGZIP() []byte {
	file_service_gonuxt_auth_proto_rawDescOnce.Do(func() {
		file_service_gonuxt_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_gonuxt_auth_proto_rawDesc), len(file_service_gonuxt_auth_proto_rawDesc)))
	})
	return file_service_gonuxt_auth_proto_rawDescData
}

var file_service_gonuxt_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_gonuxt_auth_proto_goTypes = []any{
	(*LogoutRequest)(nil),          // 0: pb.LogoutRequest
	(*LogoutResponse)(nil),         // 1: pb.LogoutResponse
	(*GoogleLoginRequest)(nil),     // 2: pb.GoogleLoginRequest
	(*GoogleLoginResponse)(nil),    // 3: pb.GoogleLoginResponse
	(*GoogleCallbackRequest)(nil),  // 4: pb.GoogleCallbackRequest
	(*GoogleCallbackResponse)(nil), // 5: pb.GoogleCallbackResponse
	(*CreateUserRequest)(nil),      // 6: pb.CreateUserRequest
	(*LoginUserRequest)(nil),       // 7: pb.LoginUserRequest
	(*CreateUserResponse)(nil),     // 8: pb.CreateUserResponse
	(*LoginUserResponse)(nil),      // 9: pb.LoginUserResponse
}
var file_service_gonuxt_auth_proto_depIdxs = []int32{
	6, // 0: pb.Auth.CreateUser:input_type -> pb.CreateUserRequest
	7, // 1: pb.Auth.LoginUser:input_type -> pb.LoginUserRequest
	2, // 2: pb.Auth.GoogleLogin:input_type -> pb.GoogleLoginRequest
	4, // 3: pb.Auth.GoogleCallback:input_type -> pb.GoogleCallbackRequest
	0, // 4: pb.Auth.Logout:input_type -> pb.LogoutRequest
	8, // 5: pb.Auth.CreateUser:output_type -> pb.CreateUserResponse
	9, // 6: pb.Auth.LoginUser:output_type -> pb.LoginUserResponse
	3, // 7: pb.Auth.GoogleLogin:output_type -> pb.GoogleLoginResponse
	5, // 8: pb.Auth.GoogleCallback:output_type -> pb.GoogleCallbackResponse
	1, // 9: pb.Auth.Logout:output_type -> pb.LogoutResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_gonuxt_auth_proto_init() }
func file_service_gonuxt_auth_proto_init() {
	if File_service_gonuxt_auth_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_login_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_gonuxt_auth_proto_rawDesc), len(file_service_gonuxt_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gonuxt_auth_proto_goTypes,
		DependencyIndexes: file_service_gonuxt_auth_proto_depIdxs,
		MessageInfos:      file_service_gonuxt_auth_proto_msgTypes,
	}.Build()
	File_service_gonuxt_auth_proto = out.File
	file_service_gonuxt_auth_proto_goTypes = nil
	file_service_gonuxt_auth_proto_depIdxs = nil
}
