// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: service_gonuxt_starter.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_gonuxt_starter_proto protoreflect.FileDescriptor

const file_service_gonuxt_starter_proto_rawDesc = "" +
	"\n" +
	"\x1cservice_gonuxt_starter.proto\x12\x02pb\x1a\x15rpc_update_user.proto\x1a\x17rpc_refresh_token.proto\x1a\x16rpc_verify_token.proto\x1a\frpc_me.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto2\xc6\x02\n" +
	"\x06GoNuxt\x123\n" +
	"\x02Me\x12\r.pb.MeRequest\x1a\x0e.pb.MeResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/v1/me\x12P\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*2\b/v1/user\x12[\n" +
	"\fRefreshToken\x12\x16.google.protobuf.Empty\x1a\x18.pb.RefreshTokenResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/v1/token/refresh\x12X\n" +
	"\vVerifyToken\x12\x16.google.protobuf.Empty\x1a\x17.pb.VerifyTokenResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/token/verifyB.Z,github.com/noueii/gonuxt-starter/internal/pbb\x06proto3"

var file_service_gonuxt_starter_proto_goTypes = []any{
	(*MeRequest)(nil),            // 0: pb.MeRequest
	(*UpdateUserRequest)(nil),    // 1: pb.UpdateUserRequest
	(*emptypb.Empty)(nil),        // 2: google.protobuf.Empty
	(*MeResponse)(nil),           // 3: pb.MeResponse
	(*UpdateUserResponse)(nil),   // 4: pb.UpdateUserResponse
	(*RefreshTokenResponse)(nil), // 5: pb.RefreshTokenResponse
	(*VerifyTokenResponse)(nil),  // 6: pb.VerifyTokenResponse
}
var file_service_gonuxt_starter_proto_depIdxs = []int32{
	0, // 0: pb.GoNuxt.Me:input_type -> pb.MeRequest
	1, // 1: pb.GoNuxt.UpdateUser:input_type -> pb.UpdateUserRequest
	2, // 2: pb.GoNuxt.RefreshToken:input_type -> google.protobuf.Empty
	2, // 3: pb.GoNuxt.VerifyToken:input_type -> google.protobuf.Empty
	3, // 4: pb.GoNuxt.Me:output_type -> pb.MeResponse
	4, // 5: pb.GoNuxt.UpdateUser:output_type -> pb.UpdateUserResponse
	5, // 6: pb.GoNuxt.RefreshToken:output_type -> pb.RefreshTokenResponse
	6, // 7: pb.GoNuxt.VerifyToken:output_type -> pb.VerifyTokenResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_gonuxt_starter_proto_init() }
func file_service_gonuxt_starter_proto_init() {
	if File_service_gonuxt_starter_proto != nil {
		return
	}
	file_rpc_update_user_proto_init()
	file_rpc_refresh_token_proto_init()
	file_rpc_verify_token_proto_init()
	file_rpc_me_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_gonuxt_starter_proto_rawDesc), len(file_service_gonuxt_starter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gonuxt_starter_proto_goTypes,
		DependencyIndexes: file_service_gonuxt_starter_proto_depIdxs,
	}.Build()
	File_service_gonuxt_starter_proto = out.File
	file_service_gonuxt_starter_proto_goTypes = nil
	file_service_gonuxt_starter_proto_depIdxs = nil
}
