// This file is auto-generated by @hey-api/openapi-ts

export type PbCreateUserRequest = {
    username?: string;
    password?: string;
};

export type PbCreateUserResponse = {
    user?: PbUser;
};

export type PbLoginUserRequest = {
    username?: string;
    password?: string;
};

export type PbLoginUserResponse = {
    user?: PbUser;
    session_id?: string;
    access_token?: string;
    access_token_expires_at?: string;
    refresh_token?: string;
    refresh_token_expires_at?: string;
};

export type PbRefreshTokenRequest = {
    refresh_token?: string;
};

export type PbRefreshTokenResponse = {
    access_token?: string;
    access_token_expires_at?: string;
};

export type PbUpdateUserRequest = {
    username?: string;
    password?: string;
    balance?: number;
};

export type PbUpdateUserResponse = {
    user?: PbUser;
};

export type PbUser = {
    id?: string;
    username?: string;
    created_at?: string;
    role?: string;
};

export type ProtobufAny = {
    '@type'?: string;
    [key: string]: unknown | string | undefined;
};

export type RpcStatus = {
    code?: number;
    message?: string;
    details?: Array<ProtobufAny>;
};

export type GoNuxtCreateUserData = {
    body: PbCreateUserRequest;
    path?: never;
    query?: never;
    url: '/v1/create_user';
};

export type GoNuxtCreateUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type GoNuxtCreateUserError = GoNuxtCreateUserErrors[keyof GoNuxtCreateUserErrors];

export type GoNuxtCreateUserResponses = {
    /**
     * A successful response.
     */
    200: PbCreateUserResponse;
};

export type GoNuxtCreateUserResponse = GoNuxtCreateUserResponses[keyof GoNuxtCreateUserResponses];

export type GoNuxtLoginUserData = {
    body: PbLoginUserRequest;
    path?: never;
    query?: never;
    url: '/v1/login_user';
};

export type GoNuxtLoginUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type GoNuxtLoginUserError = GoNuxtLoginUserErrors[keyof GoNuxtLoginUserErrors];

export type GoNuxtLoginUserResponses = {
    /**
     * A successful response.
     */
    200: PbLoginUserResponse;
};

export type GoNuxtLoginUserResponse = GoNuxtLoginUserResponses[keyof GoNuxtLoginUserResponses];

export type GoNuxtRefreshTokenData = {
    body: PbRefreshTokenRequest;
    path?: never;
    query?: never;
    url: '/v1/refresh_token';
};

export type GoNuxtRefreshTokenErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type GoNuxtRefreshTokenError = GoNuxtRefreshTokenErrors[keyof GoNuxtRefreshTokenErrors];

export type GoNuxtRefreshTokenResponses = {
    /**
     * A successful response.
     */
    200: PbRefreshTokenResponse;
};

export type GoNuxtRefreshTokenResponse = GoNuxtRefreshTokenResponses[keyof GoNuxtRefreshTokenResponses];

export type GoNuxtUpdateUserData = {
    body: PbUpdateUserRequest;
    path?: never;
    query?: never;
    url: '/v1/update_user';
};

export type GoNuxtUpdateUserErrors = {
    /**
     * An unexpected error response.
     */
    default: RpcStatus;
};

export type GoNuxtUpdateUserError = GoNuxtUpdateUserErrors[keyof GoNuxtUpdateUserErrors];

export type GoNuxtUpdateUserResponses = {
    /**
     * A successful response.
     */
    200: PbUpdateUserResponse;
};

export type GoNuxtUpdateUserResponse = GoNuxtUpdateUserResponses[keyof GoNuxtUpdateUserResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};