name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: '${{ secrets.DB_USER }}'
          POSTGRES_PASSWORD: '${{ secrets.DB_USER_PASSWORD }}'
          POSTGRES_DB: '${{ secrets.DB_NAME }}'

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:


      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test DB connection
        run: make dbconn

      - name: Set up goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Test goose
        run: goose -version

      - name: Run DB migrations
        run: make dbmigrateup

      - name: Test code
        run: make test



